import Head from 'next/head'
import Products from './components/Products'
import Sidebar from './components/Sidebar'
import axios from 'axios'
import { useState, createContext, useEffect } from 'react'
import _ from 'lodash';
const Data = createContext()

const Home = () => {
   const [posts, setPosts] = useState([])
   const [loading, setLoading] = useState(false)
   const [error, setError] = useState(null)
   //Api call url
   const url = 'https://assessment-edvora.herokuapp.com'
   useEffect(() => {
      const fetchData = async () => {
         setLoading(true)
         try {
            const result = await axios(url)
            setPosts(_.groupBy(result.data, 'product_name'))
            // setPosts(result.data)
         } catch (error) {
            setError(error)
         }
         setLoading(false)
      }
      fetchData()
   }, [])

   
  

   return (
      <div>
         <Head>
            <title>Edvora Product Landing Page</title>
            <meta name="description" content="Generated by create next app" />
         </Head>

         <main className='min-h-screen container py-8 px-4 mx-auto'>
            {loading ? (
               <h1 className='text-white'>Loading</h1>
            ) : (
               <>
                  <Data.Provider value={posts}>
                     <Sidebar />
                     <Products />
                  </Data.Provider>
               </>
            )}
         </main>
      </div>
   )
}
export default Home;
export  {Data} ;
