import Head from 'next/head'
import Products from '../components/Products'
import Sidebar from '../components/Sidebar'
import axios from 'axios'
import { ClipLoader } from 'react-spinners'
import { useState, createContext, useEffect, useLayoutEffect } from 'react'
import _ from 'lodash';
const Data = createContext()

const Home = () => {
   const [posts, setPosts] = useState([])
   const [loading, setLoading] = useState(false)
   const [error, setError] = useState(null)
   //Api call url
   const url = 'https://assessment-edvora.herokuapp.com'
   useEffect(() => {
      const fetchData = async () => {
         setLoading(true)
         try {
            const result = await axios(url)
            setPosts(result.data)
            // setPosts(result.data)
         } catch (error) {
            setError(error)
         }
         setLoading(false)
      }
      fetchData()
   }, [])



   // console.log(posts);
   return (
      <div>
         <Head>
            <title>Edvora Product Landing Page</title>
            <meta name="description" content="Generated by create next app" />
         </Head>

         <main className='min-h-screen container py-8 px-4 mx-auto'>
            {loading ? (
               <div className='flex justify-center items-center'>
                  <ClipLoader size={60} color={'white'} />
               </div>
            ) : (
               <>
                  <Data.Provider value={posts}>
                     <div className="xl:flex">
                        <Sidebar />
                        <div className='max-w-full mx-auto'>

                           <Products />
                        </div>
                     </div>
                  </Data.Provider>
               </>
            )}
         </main>
      </div>
   )
}
export default Home;
export { Data };
